---

- name: Installing prerequisites
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

- name: Adding Kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding Kubernetes APT repository
  apt_repository: repo='deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main'

- name: Installing Kubernetes
  apt:
    update_cache: yes
    pkg:
      - kubectl={{ version }}
      - kubeadm={{ version }}
      - kubelet={{ version }}

- name: Disable swap memory
  command: "swapoff -a"
  when: ansible_swaptotal_mb > 0

- name: Copying kubeadm.conf
  template: src=10-kubeadm.conf.j2 dest=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  notify: restart_kubelet
