# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.define "lb" do |lb|
    lb.vm.hostname = "lb"
    lb.vm.box = "ubuntu/focal64"
    lb.vm.network "private_network", ip: "192.168.33.31" 
    lb.vm.network "public_network"
  end

end